### ISSUE TITLE
Web scraping de dados de chuva no INMET

### ISSUE THREAD

**Issue by ErickSimoes** [Computacao-Fisica-CESAR-School/carinha#2]

**Comment by LucasGdBS** [comment]
Acho que isso pode ajudar:

https://blog.geekhunter.com.br/como-fazer-um-web-scraping-python/

Nesse rápido tutorial ele ensina como fazer o web scraping, com o beautifulsoup, do site https://www.climatempo.com.br (Coincidentemente)

**Comment by LucasGdBS** [comment]
Com a utilização da nova API que atualiza a cada 25 min não será mais necessário fazer o scraping
