### ISSUE TITLE
Especificar os caminhos para leitura de arquivo

### ISSUE THREAD

**Issue by LucasGdBS** [Computacao-Fisica-CESAR-School/carinha#21]
Ao executar o código na Rasp, ela não encontra os arquivos json para leitura/escrita.

Para correção podemos usar a função os.getcwd() diretamente na função json_read() e json_write()

**Comment by ErickSimoes** [comment]
Fiz alguns testes na Rasp que me permitiram entender melhor o problema.

Esse erro ocorre dependendo de onde parte a chamada para a execução do código. O caminho `os.getcwd()` vai retornar diferentes valores, a depender de onde está sendo executado.

Nos nossos testes, estávamos usando o **VS Code**, que executa o código partindo da raiz do projeto. Quando usamos o **Geany** ele executa a partir da localização do arquivo. Exemplo:

Considere o seguinte código no arquivo `main.py`:
```python
print(os.getcwd())
```

1 -  Rodando na raiz do projeto a saída é:
`C:\Users\<user_name>\<path_to_project>\carinha`

2 - Rodando diretamente do arquivo:
`C:\Users\<user_name>\<path_to_project>\carinha\Carinha`

De outro modo, podemos dizer que para "corrigir o problema" basta executar o código da raiz.

_P.S.: instalei o VS Code na Rasp para termos um ambiente de desenvolvimento mais parecido com o que temos usado em nossas máquinas._
